apiVersion: app/v1
kind: Deployment
metadata:
  name: Enter deployment name
  labels:
    app: ngnix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: nginx:1.14.2
        ports:
        - containerPort: 80